version: "3.8"
services:
  tibber_monitor:
    image: poepchen/tibber-energy-monitor:latest
    environment:
      - TIBBER_TOKEN=${TIBBER_TOKEN}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: unless-stopped
