version: "3.8"
services:
  tibber_monitor:
    hostname: tibber_monitor
    image: poepchen/tibber-energy-monitor:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TIBBER_TOKEN=${TIBBER_TOKEN}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - SSH_PASSWORD=${SSH_PASSWORD}
      - TZ=Europe/Amsterdam
    restart: unless-stopped


